---
title: "Assessment Workflow for FRMF (Setting #2)"
output: html_notebook
---

Set up your working directory

```{r}
setwd("YOUR_PATH/ProImput")
```

Install packages

```{r}
source("Dependencies.R")
```

Data

```{r}
raw_data <- readRDS("Data/raw_data_small.rds")
```

Data preprocessing

```{r}
log_data <- log2(raw_data)
smp <- nrow(log_data)
prt <- ncol(log_data)
smp
prt
```

Methods involved & Missing rate range

```{r}

method_name <- c("pwMean", "FRMF", "FRMF")
display_method_name <- c("Mean", "RMF", "FRMF_self")
number_of_method <- length(method_name)
misg_rate <- seq(0.15, 0.55, length.out = 5)
number_of_misg_rate <- length(misg_rate)

```

Load the best parameters

```{r}

best_parameter <- matrix(NA,
                         nrow = number_of_misg_rate,
                         ncol = number_of_method)
best_parameter[, 2] <- 3
best_parameter[, 3] <- 3

```

Number of iterations

```{r}

iteration <- 1

```

Generate the real-data-based simulated missing data

```{r}

missing_matrix <- array(0,
                        c(
                          number_of_misg_rate,
                          iteration,
                          nrow(log_data),
                          ncol(log_data)
                        ))

start_time <- Sys.time()
for (rate in 1:number_of_misg_rate) {
  for (loop in 1:iteration) {
    misg_data <- data_with_MV_mask_out(log_data,
                                       "MAR",
                                       misg_rate[rate],
                                       "max")$data_extra_MV
    
    missing_matrix[rate, loop, , ] <- misg_data
  }
}
end_time <- Sys.time()
end_time - start_time

```


```{r}
total_misg_rate <- misg_rate
for (rate in 1:number_of_misg_rate) {
  total_misg_rate[rate] <-
    100 * sum(is.na(missing_matrix[rate, 1, , ])) /
    (ncol(log_data) * nrow(log_data))
}
```


Imputation (~ 35 minutes for each iteration)

```{r}
temp <- list()
predict_matrix <- array(0,
                        c(
                          number_of_misg_rate,
                          iteration,
                          number_of_method,
                          nrow(log_data),
                          ncol(log_data)
                        ))
start_time <- Sys.time()

for (i in 1:number_of_method) {
  for (rate in 1:number_of_misg_rate) {
    for (loop in 1:iteration) {
      if (i == 3) {
        nbr_info_mat <- missing_matrix[rate, loop, , ]
      } else {
        nbr_info_mat <- NULL
      }
      
      skip_to_next <- FALSE
      
      tryCatch({
        temp[[(rate - 1) * iteration  + loop]] <-
          impute(
            log_data = missing_matrix[rate, loop, , ],
            methods = method_name[i],
            parameter = best_parameter[rate, i],
            nbr_info_mat = nbr_info_mat
          )
        
        predict_matrix[rate, loop, i, , ] <-
          temp[[(rate - 1) * iteration  + loop]]$imp
        
        
      }, error = function(error_condition) {
        message('Caught an error!')
        message(error_condition)
        skip_to_next <- TRUE
      }, finally = {
        message('Success!')
      })
      
      if (skip_to_next) {
        next
      }
    }
  }
}
end_time <- Sys.time()

end_time - start_time

```

Evaluate using NRMSE

```{r}
nrmse_matrix <- matrix(0,
                       nrow = number_of_misg_rate * number_of_method,
                       ncol = iteration)


start_time <- Sys.time()
for (rate in 1:number_of_misg_rate) {
  for (loop in 1:iteration) {
    data_extra_MV <- missing_matrix[rate, loop, ,]
    for (i in 1:number_of_method) {
      data_imputed <- predict_matrix[rate, loop, i, ,]
      nrmse_matrix[(rate - 1) * number_of_method + i, loop] <-
        data_with_MV_NRMSE(log_data, data_extra_MV, data_imputed)
    }
  }
}
end_time <- Sys.time()
end_time - start_time
```

Plot the results

```{r}
backup <- nrmse_matrix
nrmse_result <- plot_nrmse(backup,
                           display_method_name,
                           total_misg_rate,
                           "NRMSE",
                           "FRMF Workflow (Example)",
                           panel = 5)
print(nrmse_result)
```

Save the plot

```{r}
emf(file = "FRMF Workflow (Example).emf",
    width = 8,
    height = 4.8)
print(nrmse_result)
dev.off()
```

